apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    cert-manager.io/cluster-issuer: "ca-clusterissuer"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - grafana.cluster.wpc
    secretName: grafana-tls-secret
  rules:
  - host: grafana.cluster.wpc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pwa-notifier-ingress
  annotations:
    cert-manager.io/cluster-issuer: "ca-clusterissuer"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - notify.cluster.wpc
    secretName: pwa-notifier-tls-secret
  rules:
  - host: notify.cluster.wpc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pwa-notifier
            port:
              number: 80
