apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    cert-manager.io/cluster-issuer: "ca-clusterissuer"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - grafana.cluster.wpc
    secretName: grafana-tls-secret
  rules:
  - host: grafana.cluster.wpc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-pwa-ingress
  annotations:
    cert-manager.io/cluster-issuer: "ca-clusterissuer"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - monitoring.cluster.wpc
    secretName: monitoring-pwa-tls-secret
  rules:
  - host: monitoring.cluster.wpc
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: monitoring-pwa-backend
            port:
              number: 80
      - path: /webhook
        pathType: Prefix
        backend:
          service:
            name: monitoring-pwa-backend
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
      - path: /chaos-monitor
        pathType: Prefix
        backend:
          service:
            name: chaos-monitor-grafana
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-pwa-frontend
            port:
              number: 80
