apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nuage-monitoring-stack

resources:
  - ../../base
  - ingress.yaml
  - chaos-monitor-shim.yaml
  - secrets/secrets.yaml

secretGenerator:
  - name: ollama-secret
    literals:
      - api-base=http://10.20.1.30:11434
