apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nuage-monitoring-stack

resources:
  - ../../base

secretGenerator:
  - name: ollama-secret
    literals:
      - api-base=http://192.168.5.222:11434
