apiVersion: v1
kind: Secret
metadata:
  name: pwa-notifier-secret
  namespace: nuage-monitoring-stack
type: Opaque
stringData:
  VAPID_PUBLIC_KEY: XPs3FvLIbA02zFKuZDfxf4yDs1u_D8pPpH27ybZ4sow
  VAPID_PRIVATE_KEY: BITeuR2NT0-bLGNudBS_vIetvebsLv8fAbZn8LnKBXqjhtJ8TBomd8EUpBCIO0LZNGHCgfI2dBGLxjoZGM4Rt4A
  VAPID_SUBJECT: mailto:dev@example.com
  WEBHOOK_TOKEN: ""
