apiVersion: v1
kind: Secret
metadata:
  name: pwa-notifier-secret
  namespace: nuage-monitoring-stack
type: Opaque
stringData:
  VAPID_PUBLIC_KEY: BO7ymqHO2C5o8VrfGKjY1r5e9Tte-FxrJ8fqHMVUL0l1V3cBkFXUfMbAEoHAULc5Guie0dqwxo-5ak-wH32lWBs
  VAPID_PRIVATE_KEY: xQOpAb7on4EdlY6Di7syk90yU3FOHjGo3P9r7SZemeQ
  VAPID_SUBJECT: dev@example.com
  WEBHOOK_TOKEN: ""
