VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:dapHiVGpWyUC8FLG4ygJylnBr9a3QubnDSEBRK4a9WnhxKkJlMN65OzQ16ekI3IhpV/8iKDYEaME+5Yxij5d9OR/dQCYJNKmRbc7s6FwRd5FXUDnSnir,iv:f4VbFyWZ9eT4mYGeixesez7RbnXfk9h3LYxLR6XZ5H8=,tag:Y48M4Xuu5L520A0luu4bCQ==,type:str]
VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:mUD93SbquPF6HGpgieo2KY6LfNCf3DhW6Gr+CgcgQ8hzXa3vQOVsJaNuRQ==,iv:jSnP36tKr8mWt4AM/rzQHW0dQKpVkL9O7o6NiE4RXvM=,tag:4ntZR5Lcm5ej68H3A+drqQ==,type:str]
VAPID_SUBJECT: ENC[AES256_GCM,data:oBGXsIPn4+whjXZRIRvKdHn7F2S+tngnnLAEMIeTyYc=,iv:75YgELFNzdqwwDPo3xw7lNXgdoqkLmEAnjiSZkoBUnE=,tag:mHThgxQbV4HY9oduDVh+Qw==,type:str]
WEBHOOK_TOKEN: ENC[AES256_GCM,data:6+9mtk9ZceVggYHyIc0vfas81ezjTpYPqXRb3Jsi1jQGMruatbufAvnOrF7NunTgVLSG2VvIurJ9Ev8s51RIOQ==,iv:1pLima5Uq68B1SENmghN/fofZ1bkFyC73x6/yfSOTTc=,tag:qKrcsGB4kBgmhIubens6hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4KzdyNUx6cGhkNWdLTk1F
            KzVMT1dsL1JndUQyTUg5dFpIenl0Q0d1RGpzCk9pbnNlN0pRSWJTK2RBK0xoc2Vv
            bFUyeEh2eWF1YSt5WDVXVWRpdGVRR28KLS0tIGVXRzRDQ21MdXhnTG12K0lMT0Z1
            cnZsanBjQlRGc1hTc3k4NG4zcDB3UncK3Mt+pSyoo4tkKWy9SHJqVr/uzybuUTzj
            9X8p98CS3AwzXfgczgSEfhaDSOQzMaooO9WjxjMy420o3sD64tYM8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaWwwR29rR2VaWjhpamFW
            MjlOaXBGS1ZPYXVDbWtHaTdkazdrMzZOVVgwCmxlZlJrVnRGdGhuMGNhZjcrVnJ5
            MUlTejMzZHZkZnAvWXRMc1Fqc1dZNm8KLS0tIFQrK2sxQ3pGQUIycHVUcHpoM0JX
            MGNMYzZSeXdyTkJKSW0xalQrNktoYzgKBax6S+msCj3ZDJ9XIlSSPBn/AFoLVxZ9
            kumCXBIqwvPDYqV065jSQBEvU4WwSCoPloMY+qHvIbf2AVd38CTDYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T19:19:15Z"
    mac: ENC[AES256_GCM,data:Gzj99Vdm8rpuH97xo9RnaUAAS9bh+X5CNNg82mHNHBlf49CucnuvlgSuy0i6ACSyjKyL6vCmHjO5AT27cAOka+TpHCEGP8AyhYDXu6XOBbTJskOTRyHQt3VWW0fqS3wqRXDKMOuBIZCWhcrqb8ltSpm+wGV0i0AgDMAPCUFWbmk=,iv:PTAkf7BxjDmfBF/G8U1hNOaB2UzOO2RCWvzB32LQ1yM=,tag:JkSI+bVxfSG5kA0L43jCtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
