apiVersion: v1
kind: Secret
metadata:
  name: pwa-notifier-secret
  namespace: nuage-monitoring-stack
type: Opaque
stringData:
  VAPID_PUBLIC_KEY: <path:secrets/prod-secrets.yaml#VAPID_PUBLIC_KEY>
  VAPID_PRIVATE_KEY: <path:secrets/prod-secrets.yaml#VAPID_PRIVATE_KEY>
  VAPID_SUBJECT: <path:secrets/prod-secrets.yaml#VAPID_SUBJECT>
  WEBHOOK_TOKEN: <path:secrets/prod-secrets.yaml#WEBHOOK_TOKEN>
