apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - monitoring-pwa
#   - ollama.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  version: 78.2.1
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesFile: helm/prometheus-stack-custom.yaml

- name: loki-stack
  releaseName: loki-stack
  version: 2.10.2
  repo: https://grafana.github.io/helm-charts
  valuesFile: helm/loki-custom.yaml

- name: promtail
  releaseName: promtail
  version: 6.17.0
  repo: https://grafana.github.io/helm-charts
  valuesFile: helm/promtail-custom.yaml

- name: holmes
  releaseName: holmesgpt
  version: 0.34.0
  repo: https://robusta-charts.storage.googleapis.com
  valuesFile: helm/holmesgpt-custom.yaml
