modelList:
  local-model:
    api_key: "none"
    model: "ollama_chat/sorc/qwen3.5-claude-4.6-opus:9b"
    temperature: 0
    num_ctx: 16384

logLevel: DEBUG

additionalEnvVars:
  - name: MODEL
    value: "local-model"
  - name: OLLAMA_API_BASE
    valueFrom:
      secretKeyRef:
        name: ollama-secret
        key: api-base

toolsets:
  prometheus/metrics:
    enabled: true
    config:
      prometheus_url: http://kube-prometheus-stack-prometheus.nuage-monitoring-stack.svc.cluster.local:9090
  grafana/loki:
    enabled: true
    config:
      api_url: http://loki-stack.nuage-monitoring-stack.svc.cluster.local:3100
